server.port=8080
youtube.api.key=${YOUTUBE_API_KEY}
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtubr.api.search.url=${youtube.api.base.url}/search
youtubr.api.videos.url=${youtube.api.base.url}/videos

replicate.api.token=YOUR_REAL_REPLICATE_API_KEY
#max no of relates videos to fetch
youtube.api.max.related.videos=5